# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ufo.com:
    container_name: orderer.ufo.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ufo.com/orderers/orderer.ufo.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ufo.com/orderers/orderer.ufo.com/tls/:/var/hyperledger/orderer/tls
        - orderer.ufo.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.sales.ufo.com:
    container_name: peer0.sales.ufo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sales.ufo.com
      - CORE_PEER_ADDRESS=peer0.sales.ufo.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sales.ufo.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sales.ufo.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sales.ufo.com:7051
      - CORE_PEER_LOCALMSPID=SalesMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sales.ufo.com/peers/peer0.sales.ufo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sales.ufo.com/peers/peer0.sales.ufo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.sales.ufo.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.sales.ufo.com:
    container_name: peer1.sales.ufo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.sales.ufo.com
      - CORE_PEER_ADDRESS=peer1.sales.ufo.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.sales.ufo.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sales.ufo.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sales.ufo.com:7051
      - CORE_PEER_LOCALMSPID=SalesMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sales.ufo.com/peers/peer1.sales.ufo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sales.ufo.com/peers/peer1.sales.ufo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.sales.ufo.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.customer.ufo.com:
    container_name: peer0.customer.ufo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.customer.ufo.com
      - CORE_PEER_ADDRESS=peer0.customer.ufo.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.customer.ufo.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customer.ufo.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.customer.ufo.com:10051
      - CORE_PEER_LOCALMSPID=CustomerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer.ufo.com/peers/peer0.customer.ufo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer.ufo.com/peers/peer0.customer.ufo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.customer.ufo.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.customer.ufo.com:
    container_name: peer1.customer.ufo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.customer.ufo.com
      - CORE_PEER_ADDRESS=peer1.customer.ufo.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.customer.ufo.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.customer.ufo.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customer.ufo.com:9051
      - CORE_PEER_LOCALMSPID=CustomerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/customer.ufo.com/peers/peer1.customer.ufo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/customer.ufo.com/peers/peer1.customer.ufo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.customer.ufo.com:/var/hyperledger/production
    ports:
      - 10051:10051
