# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ufo.com:
  peer0.sales.ufo.com:
  peer1.sales.ufo.com:
  peer0.customer.ufo.com:
  peer1.customer.ufo.com:
  ca.sales.ufo.com:
  ca.customer.ufo.com:

networks:
  byfn:

services:
  ca.sales.ufo.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sales.ufo.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales.ufo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales.ufo.com_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/sales.ufo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sales.ufo.com
    networks:
      - byfn

  ca.customer.ufo.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.customer.ufo.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.customer.ufo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca.customer.ufo.com_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/customer.ufo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.customer.ufo.com
    networks:
      - byfn
  
  orderer.ufo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ufo.com
    container_name: orderer.ufo.com
    networks:
      - byfn

  orderer2.ufo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer2.ufo.com
    container_name: orderer2.ufo.com
    networks:
      - byfn
  
  orderer3.ufo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer3.ufo.com
    container_name: orderer3.ufo.com
    networks:
      - byfn
    
  orderer4.ufo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer4.ufo.com
    container_name: orderer4.ufo.com
    networks:
      - byfn

  orderer5.ufo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer5.ufo.com
    container_name: orderer5.ufo.com
    networks:
      - byfn

  peer0.sales.ufo.com:
    container_name: peer0.sales.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sales.ufo.com
    networks:
      - byfn

  peer1.sales.ufo.com:
    container_name: peer1.sales.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sales.ufo.com
    networks:
      - byfn

  peer0.customer.ufo.com:
    container_name: peer0.customer.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.customer.ufo.com
    networks:
      - byfn

  peer1.customer.ufo.com:
    container_name: peer1.customer.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.customer.ufo.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.sales.ufo.com:7051
      - CORE_PEER_LOCALMSPID=SalesMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.ufo.com/peers/peer0.sales.ufo.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.ufo.com/peers/peer0.sales.ufo.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.ufo.com/peers/peer0.sales.ufo.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales.ufo.com/users/Admin@sales.ufo.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ufo.com
      - orderer2.ufo.com
      - orderer3.ufo.com
      - orderer4.ufo.com
      - orderer5.ufo.com
      - peer0.sales.ufo.com
      - peer1.sales.ufo.com
      - peer0.customer.ufo.com
      - peer1.customer.ufo.com
      - ca.sales.ufo.com
      - ca.customer.ufo.com
    networks:
      - byfn
