# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ufo.com:
  peer0.sales.ufo.com:
  peer1.sales.ufo.com:
  peer0.customer.ufo.com:
  peer1.customer.ufo.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sales
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales.ufo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.sales.ufo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sales.ufo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSales
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-customer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.customer.ufo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.customer.ufo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/customer.ufo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCustomer
    networks:
      - byfn

  orderer.ufo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ufo.com
    container_name: orderer.ufo.com
    networks:
      - byfn

  peer0.sales.ufo.com:
    container_name: peer0.sales.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sales.ufo.com
    networks:
      - byfn

  peer1.sales.ufo.com:
    container_name: peer1.sales.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sales.ufo.com
    networks:
      - byfn

  peer0.customer.ufo.com:
    container_name: peer0.customer.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.customer.ufo.com
    networks:
      - byfn

  peer1.customer.ufo.com:
    container_name: peer1.customer.ufo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.customer.ufo.com
    networks:
      - byfn
